### ISSUE TITLE
Ensure that the "tags" parameter is always a list

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/dogapi#106]
When the user sets the `tags` option with something, ensure that it is just a list of strings (not something nested), it will warn the user that the point tag set is malformed and avoid rejecting it much later in the backend.

**Comment by technovangelist** [comment]
@yannmh do recent changes mean that this is now closed?

**Comment by yannmh** [comment]
@technovangelist I am progressively sorting opened issues and moving them to https://github.com/DataDog/datadogpy

**Comment by yannmh** [comment]
Closing as solved in [datadogpy](https://github.com/DataDog/datadogpy). Thanks !
