### ISSUE TITLE
Incomplete dogapi histograms

### ISSUE THREAD

**Issue by LotharSee** [DataDog/dogapi#113]
I'm not sure if the problem come from dogapi or the way we use it.

Some histograms report incomplete percentiles.

![screen shot 2014-09-29 at 5 12 07 pm](https://cloud.githubusercontent.com/assets/2720261/4449580/55734c4a-481d-11e4-857d-a46b12ded608.png)

Some metrics only have the 95th percentile, while they all run the same version of dogapi.
And we should report more: https://github.com/DataDog/dogapi/blob/master/src/dogapi/stats/metrics.py#L73

Thanks @miketheman for noticing it.

**Comment by yannmh** [comment]
Closing and reopening on  [datadogpy](https://github.com/DataDog/datadogpy) repo.
