### ISSUE TITLE
Add host muting to the API

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dogapi#118]
This feature has been released and is now enabled for orgs that suscribed to the scope_muting beta.

It is possible to use the API via Curl to do so: https://gist.github.com/wang-arthur/d4aee2a0dea755551655#host-muting

But this feature is not yet available with a Python client.
Customer request about it here: https://datadog.desk.com/agent/case/18461

**Comment by yannmh** [comment]
Fixed in [datadogpy](https://github.com/DataDog/datadogpy). Closing.
