### ISSUE TITLE
Event tags are sent as a string

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/dogapi#123]
Our docs say we accept a "list" of tags, but we send them as a comma-separate string.

This is where it happens: https://github.com/DataDog/dogapi/blob/master/src/dogapi/http/events.py#L140-L141

**Comment by yannmh** [comment]
Thanks Conor.
The new documentation coming with Datadogpy clarifies this point: `tags` parameter type is a comma separated string.

**Comment by yannmh** [comment]
Issue is fixed in [datadogpy](https://github.com/DataDog/datadogpy). Closing.
