### ISSUE TITLE
Backward compatibility issues with monitor updates

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dogapi#132]
To reproduce, I created a monitor (id='156509').

monitor = { "id": 156509,
"name": "Test monitor - after modification",
"message": "Test message after modification",
"query": "avg(last_1h):(aws.ebs.volume_write_ops{name:prod-live-lswcore-elasticsearch,region:eu-west-1,device:/dev/xvdf} by {host} + aws.ebs.volume_read_ops{name:prod-live-lswcore-elasticsearch,region:eu-west-1,device:/dev/xvdf} by {host}) / 300 > 900",
 }
}
api.update_monitor(monitor["id"], monitor["query"], name=monitor["name"], message=monitor["message"])

>>> {'errors': ["The parameter 'type' is required"]}

Is this something you can reproduce and fix?

**Comment by yannmh** [comment]
Hey @MartinDatadog. `dogapi` was deprecated at the time of your issue post. Did you have a try with [datadogpy](https://github.com/DataDog/datadogpy) ? I don't have any issue
