### ISSUE TITLE
Ability to set API key system wide

### ISSUE THREAD

**Issue by danieljimenez** [DataDog/dogapi#133]
I love using `dogwrap` on my cron jobs. I would like to be able to set the API key system wide so that I each of my cron tasks don't end up looking like this:

```
45 1 * * * root dogwrap -k 'ffffffffffffffffffffffffffffffff' -n 'Database Backup: blah blah' -m all '/usr/local/bin/pgbackup'
```

Also if I need to rotate keys, I could change them easily all in one place.

Thanks!

**Comment by yannmh** [comment]
Thanks for your suggestion @danieljimenez. 

`dogapi` is deprecated, and `dogwrap ` is now part of [`datadog`](https://github.com/DataDog/datadogpy) package. 
We are releasing a new version v0.4.0 which includes the ability to set your API parameters with environment variables. 
Feel free to reopen this case on [`datadog`] (https://github.com/DataDog/datadogpy) repo if this solution does not suit your use case.
