### ISSUE TITLE
merge statsd + api libraries and clean up the API's

### ISSUE THREAD

**Issue by clutchski** [DataDog/dogapi#51]
Nothing pressing here, but as it stands we are recommending two python libs - one for API and one for stats. We should only have one. I've been thinking a little bit about cleaning up the API interface. I'd like something lie this:

```
import datadog
datadog.api_key = 'asdf'

# HTTP event posts
api = datadog.api('api_k)
api.event('aa')
api.comment('whatever')

# statsd requests
stats = datadog.statsd(host, port)
stats.gauge('...')

# in-process statsd (useful for heroku et al where we can't run an agent) 
stats = datadog.threaded_stats(api_key)
stats.gauge('...')
```

We have all the plumbing in place in dogapi, we just need to:
- a release a new major version (or a library with a new name so people don't have a backwards compatibility issues)
- remove old references from the docs
- deprecate the old versions

**Comment by yannmh** [comment]
Issue is fixed in [datadogpy](https://github.com/DataDog/datadogpy). Closing.
