### ISSUE TITLE
Datadog Fabric task doesn't respect aliases

### ISSUE THREAD

**Issue by MisterRayCo** [DataDog/dogapi#56]
Datadog's annotation @notify "eats" aliases.
E.g. I cant execute this task with alias "all" I can execute it only with it's name "install" having this configuration:

```
@notify
@task(alias="all", default=True)
def install(): 
...
```

**Comment by yannmh** [comment]
Closing and reopening on  [datadogpy](https://github.com/DataDog/datadogpy) repo.
