### ISSUE TITLE
dog_http_api should support HTTP proxying

### ISSUE THREAD

**Issue by alq666** [DataDog/dogapi#72]
`http_client` has `.set_tunnel` starting with python 2.7, which `http_client` may not honor the `https_proxy` environment variable.

**Comment by yannmh** [comment]
Datadogpy switched to `requests` library. 
It natively supports environment variables `HTTP_PROXY` and `HTTPS_PROXY`.
Also, we allow users to set their proxy settings at api initialization.
```python
from datadog import initialize, api

proxies = {
  "http": "http://10.10.1.10:3128",
  "https": "http://10.10.1.10:1080",
}

options = {
    'api_key': 'api_key',
    'app_key': 'app_key',
    'proxies': proxies
}

initialize(**options)

api.Event.create(...)

```

**Comment by yannmh** [comment]
Fixed in [datadogpy](https://github.com/DataDog/datadogpy). Closing.
